### ISSUE TITLE
Credits Medley music doesn't stop

### ISSUE THREAD

**Issue by objShaggy** [femloy/OpenTower#41]
The music medley during the credits does not stop, ever.

https://github.com/user-attachments/assets/3ebfe80e-3da4-4efe-81e7-b0e0f8290c69

**Comment by portablenetworkgraphix** [comment]
use the runtime specified in the [README.md](https://github.com/femloy/OpenTower/blob/main/README.md) to fix the font, plus the repository doesnt include a editable FMOD project, so once again this an issue with the user not the decomp itself.

theres no need to upload multiple issues over a user created error. so before submitting, please try to fix it yourself instead of having other people fix an error that isnt even the decomp's fault.
